[package]
name = "dirh"
version = "0.1.0"
authors = ["Clement Tsang <cjhtsang@uwaterloo.ca>"]
edition = "2021"
keywords = ["cli", "hash", "checksum"]
license = "Apache-2.0"
categories = ["command-line-utilities"]
readme = "README.md"
description = "A small utility to get a hash of either a file or a directory"

[profile.dev.package."*"]
opt-level = 3 # Compile dependencies with optimizations on even in debug mode.

[profile.release]
debug = 0
strip = "symbols"
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
anyhow = "1.0.71"
blake3 = { version = "1.3.3", features = ["rayon"] }
clap = { version = "4.2.7", features = ["derive"] }
md5 = "0.7.0"
rayon = "1.7.0"
sha1 = "0.10.5"
sha2 = "0.10.6"
sha3 = "0.10.8"
