[package]
name = "dircs"
version = "0.1.8"
authors = ["Clement Tsang <cjhtsang@uwaterloo.ca>"]
edition = "2021"
repository = "https://github.com/ClementTsang/dircs"
keywords = ["cross-platform", "cli", "hash", "checksum"]
license = "Apache-2.0"
categories = ["command-line-utilities"]
description = "A small cross-platform utility to get the hash of a file or directory."
readme = "README.md"
rust-version = "1.70.0"
exclude = [".github", ".markdownlint.json", "CHANGELOG.md"]

[[bin]]
name = "dircs"
path = "src/main.rs"
doc = false

[profile.dev.package."*"]
opt-level = 3 # Compile dependencies with optimizations on even in debug mode.

[profile.release]
debug = 0
strip = "symbols"
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
anyhow = "1.0.75"
blake2 = "0.10.6"
blake3 = { version = "1.5.0", features = ["rayon"] }
clap = { version = "4.4.8", features = ["derive"] }
hex = "0.4.3"
jwalk = "0.8.1"
md5 = "0.7.0"
memmap2 = "0.9.0"
rayon = "1.8.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
sha3 = "0.10.8"

[dev-dependencies]
assert_cmd = "2.0.12"

[lints.rust]
rust_2018_idioms = "deny"
missing_docs = "deny"
unused_extern_crates = "deny"

[lints.clippy]
todo = "deny"
unimplemented = "deny"
missing_safety_doc = "deny"
