[package]
name = "dircs"
version = "0.1.7"
authors = ["Clement Tsang <cjhtsang@uwaterloo.ca>"]
edition = "2021"
repository = "https://github.com/ClementTsang/dircs"
keywords = ["cross-platform", "cli", "hash", "checksum"]
license = "Apache-2.0"
categories = ["command-line-utilities"]
description = "A small cross-platform utility to get a hash of a file or directory."
readme = "README.md"
rust-version = "1.69.0"
exclude = [".github", ".markdownlint.json", "CHANGELOG.md"]

[[bin]]
name = "dircs"
path = "src/main.rs"
doc = false

[profile.dev.package."*"]
opt-level = 3 # Compile dependencies with optimizations on even in debug mode.

[profile.release]
debug = 0
strip = "symbols"
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
anyhow = "1.0.71"
blake3 = { version = "1.3.3", features = ["rayon"] }
clap = { version = "4.3.5", features = ["derive"] }
hex = "0.4.3"
jwalk = "0.8.1"
md5 = "0.7.0"
memmap2 = "0.7.0"
rayon = "1.7.0"
sha1 = "0.10.5"
sha2 = "0.10.7"
sha3 = "0.10.8"

[dev-dependencies]
assert_cmd = "2.0.11"
